### ISSUE TITLE
AC86U，官改3.0.0.4.384_32799_koolshare固件，无法离线安装

### ISSUE THREAD

**Issue by songc1992** [hq450/fancyss_history_package#10]
软件中心版本 1.3.6

【2018年11月23日 21:10:33】: ====================== step 1 ===========================
【2018年11月23日 21:10:33】: 开启软件离线安装！
【2018年11月23日 21:10:34】: /tmp/upload目录下检测到上传的离线安装包shadowsocks.tar.gz
【2018年11月23日 21:10:35】: 尝试解压离线安装包离线安装包
【2018年11月23日 21:10:36】: 解压错误，错误代码：1！
【2018年11月23日 21:10:36】: 估计是错误或者不完整的的离线安装包！
【2018年11月23日 21:10:36】: 删除相关文件并退出...
【2018年11月23日 21:10:36】: ======================== end ============================

请问如何解决？

**Comment by demonrain** [comment]
@songc1992 你可能是直接右键另存为，下了个几十K的文件，原文件大小13M的

**Comment by songc1992** [comment]
经你提点，我删除了Chrome的迅雷关联，然后问题解决，多谢！
