### ISSUE TITLE
ac-88u研发384固件现在到什么进度了？

### ISSUE THREAD

**Issue by leiyu8850** [hq450/fancyss_history_package#30]
从去年5余额8号（380.70_0-X7.9.1 ）一直到现在快1年了,而梅林固件已经更新到了384.10.2。在这里不是想催促研发的大神，只是想了解下进度。当然有的朋友说已经停更了，拜托说停更的朋友，可以拿出证据来吗？GitHub我是没有看到大神说停更的消息，当然也有人说大神再群里说了，我没加群看不到大神说什么，如果你看到了，还麻烦把聊天记录贴出来。另外想告诉开发的大神，其实还有很多人都再使用ac88u（和其他较老型号的路由），也请大神们不要放弃后续的开发。虽然做固件没有回报，但是有很多拥护你们的粉丝对你的期待……望大神更新。
（PS：也希望能和大神们一起讨论或交流问题，咱们有这个论坛作为平台，希望能你能够看到并回复我）
hq450

**Comment by z991238** [comment]
不是说不开发了，而是旧平台实在是跟不上节奏了，内核旧，bcm也不给上3.X内核。这是限制开发主要源头，2.6内核很多东西都支持不完善，或者是是支持很差，主要是要求需要3.X以上内核，况且490X发布以后你看维护多积极，唯一的办法就是叫BCM源头上给你更新内核才有用

**Comment by z991238** [comment]
旧平台2.6.X内核都用了多少年了，很多固件新特性包括插件多线程之类都只能通过新内核去调度各cpu实现，老毛子支持多线程都是要3.X内核，虽然也是万年不更新内核固件，但是好歹他也支持到最低版本基础，所以现在你还买40nm的470X系列就是太可爱了。这个适合做AP，相当不为过。拿来折腾就差很多

**Comment by z991238** [comment]
老机型384是没有停更，更多只是安全性升级，没有什么实质性变化，毕竟产品老旧，梅林那边老机型384据说适配难度大，资源占用高，所以你还在期待嘛

**Comment by leiyu8850** [comment]
非常感谢兄弟的回复，原本的想法有2
1 了解下380.70_0-X7.9.1后续的开发是否已经终结了
2 就是想了解一下具体遇到什么问题，因为本身也是做开发的，自己身边也有资源，如果可以的话，可以一同解决遇到的问题。但是看到大神的回复，似乎觉得自己优质了，呵呵

**Comment by leiyu8850** [comment]
其实最近也有考虑配置一个软路由，毕竟X86的处理性能要比ARM再运算上强不少，但是后来一想即便是配置一个低功耗的X86也比现在的硬路由耗电，且7*24的超长工作，发热量等等因素，没有硬路由有优势。兄弟可有推荐的路由器型号，或者软路由呢？

**Comment by leiyu8850** [comment]
> 不是说不开发了，而是旧平台实在是跟不上节奏了，内核旧，bcm也不给上3.X内核。这是限制开发主要源头，2.6内核很多东西都支持不完善，或者是是支持很差，主要是要求需要3.X以上内核，况且490X发布以后你看维护多积极，唯一的办法就是叫BCM源头上给你更新内核才有用

**Comment by leiyu8850** [comment]
非常感谢兄弟的回复，原本的想法有2
1 了解下380.70_0-X7.9.1后续的开发是否已经终结了
2 就是想了解一下具体遇到什么问题，因为本身也是做开发的，自己身边也有资源，如果可以的话，可以一同解决遇到的问题。但是看到大神的回复，似乎觉得自己幼稚了，呵呵
其实最近也有考虑配置一个软路由，毕竟X86的处理性能要比ARM再运算上强不少，但是后来一想即便是配置一个低功耗的X86也比现在的硬路由耗电，且7*24的超长工作，发热量等等因素，没有硬路由有优势。
兄弟可有推荐的路由器型号，或者软路由呢？(cpu、主板等，或者给个淘宝连接也行)




------------------ 原始邮件 ------------------
发件人: "z991238"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 中午1:50
收件人: "hq450/fancyss_history_package"<fancyss_history_package@noreply.github.com>;
抄送: "sunny"<10250378@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hq450/fancyss_history_package] ac-88u研发384固件现在到什么进度了？ (#30)




不是说不开发了，而是旧平台实在是跟不上节奏了，内核旧，bcm也不给上3.X内核。这是限制开发主要源头，2.6内核很多东西都支持不完善，或者是是支持很差，主要是要求需要3.X以上内核，况且490X发布以后你看维护多积极，唯一的办法就是叫BCM源头上给你更新内核才有用

**Comment by leiyu8850** [comment]
> 旧平台2.6.X内核都用了多少年了，很多固件新特性包括插件多线程之类都只能通过新内核去调度各cpu实现，老毛子支持多线程都是要3.X内核，虽然也是万年不更新内核固件，但是好歹他也支持到最低版本基础，所以现在你还买40nm的470X系列就是太可爱了。这个适合做AP，相当不为过。拿来折腾就差很多

非常感谢兄弟的回复，原本的想法有2
1 了解下380.70_0-X7.9.1后续的开发是否已经终结了
2 就是想了解一下具体遇到什么问题，因为本身也是做开发的，自己身边也有资源，如果可以的话，可以一同解决遇到的问题。但是看到大神的回复，似乎觉得自己幼稚了，呵呵
